name: Workflow

on:
  push:
    branches:
      - main
      - branch-[0-9]+.[0-9]+

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - run: |
          pip install -r requirements.txt
      - run: |
          git clone https://github.com/cdarlint/winutils
      - name: Run python tests
        shell: bash
        run: |
          # Set Hadoop environment variables required for testing Spark integrations on Windows
          export HADOOP_HOME=`realpath winutils/hadoop-3.2.2`
          export PATH=$PATH:$HADOOP_HOME/bin

          python example.py

  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - run: |
          pip install -r requirements.txt
      - name: Run python tests
        shell: bash
        run: |
          python example.py
